# app.yaml
runtime: nodejs20 # Use the latest LTS version of Node supported by GCP

# App Engine routes traffic to port 8080 automatically
env_variables:
  NODE_ENV: 'production'
  # App Engine connects to Cloud SQL via Unix Sockets natively using this path:
  DB_HOST: '/cloudsql/projects/389077935832/secrets/dev-CLOUD_SQL_INSTANCE_CONNECTION_NAME'
  DB_PORT: '5432'
  DB_NAME: 'dev-DB_NAME'
  DB_USER: 'dev-DB_USER'
  JWT_EXPIRES_IN: '7d'
  RESET_TOKEN_EXPIRES_MINUTES: '30'
  FROM_EMAIL: 'noreply@yourdomain.com'
  CLOUD_SQL_INSTANCE_CONNECTION_NAME: 'projects/389077935832/secrets/dev-CLOUD_SQL_INSTANCE_CONNECTION_NAME'
